### PR TITLE
add some tests

### PR DESCRIPTION
**Pull request by xjamundx**
all tests pass with this and there is a slightly clearer area explaining in the tests what is still acting weirdly

### CODE REVIEW

**Comment by xjamundx** [comment]
feel free to just manually pull this into your PR, no need to give me any credit

**Comment by xjamundx** [comment]
one more test coming..

**Comment by platinumazure** [comment]
Thanks @xjamundx. Would you mind rebasing with eslint master? I rebased this morning and now I can't merge easily-- sorry-- my fault...

**Comment by xjamundx** [comment]
sure

**Comment by xjamundx** [comment]
Updated my stuff. Checking the tests.

**Comment by platinumazure** [comment]
Merging now. Rebasing with no conflicts is no fun but at least I merged first this time.

**Comment by xjamundx** [comment]
haha good work!

**Comment by xjamundx** [comment]
By all means just copy/paste my changes into your code and take all the credit

**Comment by platinumazure** [comment]
Nah, I'll mention you in the commit message body at least, if I can't fit you into the first line.

**Comment by platinumazure** [comment]
Thanks! Merged, rebase with eslint master, and force pushed to my PR.

**Pull request closed without merging**
